version: "3"
networks:
  loki:

services:
  loki:
    image: grafana/loki:2.3.0
    volumes:
      - /opt/loki/config/loki-config.yml:/etc/loki/loki-config.yml
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.3.0
    volumes:
      - /opt/loki/config/promtail-config.yml:/etc/promtail/promtail-config.yml
      - /var/lib/docker/containers/:/var/lib/docker/containers/
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki